Add privacy notice
TNG/next-generation-scrum-poker pull request #77
Opened 2021-09-10 13:06 UTC by lukastaegert

This is a first draft for adding a privacy notice. This still needs legal review and may me incomplete. Also, wording improvements are welcome.

<img width="338" alt="Bildschirmfoto 2021-09-10 um 15 05 40" src="https://user-images.githubusercontent.com/12949268/132857716-d31dfd6d-bbc3-4a15-aa85-6f732cfc2832.png">
<img width="304" alt="Bildschirmfoto 2021-09-10 um 15 05 49" src="https://user-images.githubusercontent.com/12949268/132857728-ba3606a6-45f6-4b95-80af-215d4b25d4a2.png">

2022-02-04 15:02 UTC, ThiloAschebrock reviewed
This definitively fulfills its purpose. However, the current design in a long column does not feel optimal to me:

- On a normal screen, there is plenty of horizontal screen to fit all of the three columns next to each other.
- Clicking on the link to view the privacy details, leads to a big layout jump of the all already visible elements to the top.

Suggestion:
- Use a grid-layout that auto fills the available space so that the four boxes are displayed in a row and only break into multiple rows if the screen width is decreased.
- Instead of centering the normal login screen, place it at fixed fraction of the view port height. This way it will not jump up if content below appears.
-> yes it jumps, but would left it to an improvement, i dont expect to many people reading it regulary

2022-02-04 15:04 UTC, ThiloAschebrock commented on frontend/src/Components/LoginPage/LoginPage.tsx
> +        <PrivacyNoticeContainer />
Can we remove the div-wrapper and pass the class to `PrivacyNoticeContainer` direclty?

2022-02-04 15:09 UTC, ThiloAschebrock commented on frontend/src/Components/PrivacyNoticeContainer/PrivacyNoticeContainer.test.tsx
> +    expect(queryAllByText('Processing of Personal Data')).toHaveLength(0);
I am only familiar with `@testing-library/react`. With that library, I would have written:

```typescript
expect(queryByText('Processing of Personal Data')).not.toBeInTheDocument();
```
This doesn't work. Can you explain while the interface is a bit different for `preact`?

2022-02-04 15:09 UTC, ThiloAschebrock commented on frontend/src/Components/PrivacyNoticeContainer/PrivacyNoticeContainer.test.tsx
> +import { fireEvent } from '@testing-library/preact';
'@testing-library/preact' is duplicated.

2022-02-04 18:22 UTC, andreashille requested changes
We should clarify the Note with legal, i‘m on it.

2022-03-04 14:07 UTC, ThiloAschebrock approved these changes

2022-03-04 14:15 UTC, andreashille approved these changes

2022-03-04 14:17 UTC, merged

2022-03-05 13:38 UTC, lukastaegert commented
Sorry, kind of missed the review comments on this one. One major issue I have is that while the entire page is in English, the privacy notice is now in German, which feels both inconsistent and unprofessional to me. Do we have an English translation or should we just translate it ourselves?